### ISSUE TITLE
support request: Setting the `karate.config.dir` parameter

### ISSUE THREAD

**Issue by jimkont** [karatelabs/vscode-extension#1]
I am testing the Karate VSCode plugin and when I run the tests all fail by not being able to read the `karate-config.js`. I think I need to specify the `karate somehow.config.dir` variable to e.g. `src/intTest/kotlin` but not sure where I can do that. The project is configured with gradle if that helps

Do I have to specify some custom launch.json configuration or change the extension settings?

Thanks in advance for your help

**Comment by ptrthomas** [comment]
@jimkont thank you for trying the plugin, yes this first version focuses on making it easy to run tests without maven or gradle.  can you try this - change the "mode" in the extension settings to `custom`, see screenshot below

<img width="607" alt="image" src="https://user-images.githubusercontent.com/915480/188869976-d3b5e87e-8bf8-4036-850d-2744ba7346a0.png">

and then refer to the docs here: https://github.com/karatelabs/karate/wiki/Debug-Server#gradle

if you still have problems, please zip and send a sample project so that I can test and verify the extension works before the next release

**Comment by jimkont** [comment]
thanks for the prompt response @ptrthomas , I did not manage to set this up but, tbh, I did not put too much effort because I decided to switch to IntelliJ in the meantime. testing / debugging works out of the box there

**Comment by ptrthomas** [comment]
@jimkont thanks for the feedback. maven and gradle debugging should work in this plugin as far as I know, but yes it does require a settings tweak. in the future we would like to detect and tightly integrate with the vscode Java extension when available - but we are not there yet

happy to take feedback on the intellij plugin: https://plugins.jetbrains.com/plugin/19232-karate
