### ISSUE TITLE
Since the last update of the extension and the change in the login does not work for me

### ISSUE THREAD

**Issue by adrianSuarezGomez** [karatelabs/vscode-extension#20]
Hello,
Before the update the extension worked correctly, click on "Run" and the test was executed. Since February 29th, now I click on "Run" and it does nothing, the test does not run and it does not show me an error in the console.

I am testing it with a new example project.

If I run the test by console with "mvn clean test" it works correctly.

I attach a gif where you can see that when I click on "Run" nothing is executed, and when I run it by console it works.
![2024-03-02_12h19_50](https://github.com/karatelabs/vscode-extension/assets/67955214/5c32fba4-15b0-4883-9c6b-d4911b3113c8)

I don't know what more information to attach as no error message is shown in the console.
Thanks!

**Comment by ptrthomas** [comment]
@adrianSuarezGomez since `mvn` works - try changing the extension settings by clicking on the gear icon: 
<img width="551" alt="image" src="https://github.com/karatelabs/vscode-extension/assets/915480/bb7ebbe0-a446-4785-815d-c3a448f296c9">

then switch run mode to `custom`
<img width="675" alt="image" src="https://github.com/karatelabs/vscode-extension/assets/915480/b166b221-67c4-4e4b-8411-3f086bb73abb">

let me know if that works.

the next thing to try is to make sure you have the VS Code Java extension installed: https://marketplace.visualstudio.com/items?itemName=redhat.java - I think this is why `Run >>` was not working for you, refer the new documentation: https://github.com/karatelabs/vscode-extension#settings

also there is a Karate Log that you can view in the "Output" tab at the bottom, screenshot below:
![image](https://github.com/karatelabs/vscode-extension/assets/915480/d9e90482-a5bc-4e9d-85e6-2d0460752d08)

if you are still stuck, feel free to revert to the old version - you can do it from VS code. if you email us at info AT karatelabs DOT io - I will be happy to get on a call to troubleshoot

**Comment by adrianSuarezGomez** [comment]
@ptrthomas Thank you for your support.
Now I see that the Output displays an error, it is as follows:
![Screenshot 2024-03-02 165007](https://github.com/karatelabs/vscode-extension/assets/67955214/e755e374-32d5-4f47-937a-549a533c3df6)
I have the java extension installed in VS code.
My java version is:
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment Temurin-11.0.22+7 (build 11.0.22+7)
OpenJDK 64-Bit Server VM Temurin-11.0.22+7 (build 11.0.22+7, mixed mode)

**Comment by ptrthomas** [comment]
@adrianSuarezGomez to be honest I'm not sure what's going on. can you try re-starting VS Code and make sure you are in Administrator mode ? also feel free to fall-back to the older version of the plugin

we will keep this issue open and do some investigations on windows. one more thing to try is ensure that your system `PATH` is also synced with VS Code - there are some tips in this thread: https://stackoverflow.com/questions/42545885/vs-code-error-spawn-git-enoent

**Comment by ptrthomas** [comment]
@adrianSuarezGomez I'm closing this for now, we've also released a new version that improves the logging and support for running karate in standalone / custom mode: https://github.com/karatelabs/vscode-extension#standalone
